name: python-gpu-env

channels:
  - conda-forge
  - defaults

dependencies:
  - bokeh
  - dask
  - datashader
  - gh
  - git
  - holoviews
  - hvplot
  - ipywidgets
  - jupyterlab
  - jupyterlab-git
  - jupyterlab-nvdashboard
  - jupyterlab-lsp
  - matplotlib
  - nbgitpuller
  - numba
  - numpy
  - panel
  - pip
  - pip:
    - -r requirements.txt
  - pyarrow
  - python
  - python-language-server
  - pyviz_comms
  - wandb
  - xgboost
